spring.application.name=tienda

# Carga variables desde .env en la raíz del proyecto (si existe)
spring.config.import=optional:file:.env[.properties]

# Se define el puerto por el que se escucha el servidor web.
server.port=80

# Se define el formato de hora del log de la consola.
logging.pattern.dateformat=hh:mm

# Se evita el mensaje de SPRING en banner
spring.main.banner-mode=off

# Se evita el uso de cache en desarrollo, luego, en producción sí.
spring.thymeleaf.cache=false

#Conexión a la BD Techshop en MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/techshop}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

#Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=${FIREBASE_BUCKET_NAME}
firebase.storage.path=${FIREBASE_STORAGE_PATH}
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH}

#Propiedades para enviar correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
